programming style changed

diff --git a/mare b/mare
--- a/mare
+++ b/mare
@@ -18,21 +18,8 @@
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-#################################
-#           VARIABLES           #
-#################################
-
 LC_ALL=C
 export LC_ALL
-
-FILE_SIZE=$(cat /usr/share/mare/version.list | head -n1)
-BASH=0
-PACKAGE_MANAGER=0
-COMMAND="$1"
-
-#################################
-# 			FUNCTION			#
-#################################
 
 # Check used tools for their presence in the operating system
 check_utils()
@@ -54,7 +41,7 @@ check_utils()
 	echo "/bin/sh link to ${SH}"
 	
 	if [ -x /usr/bin/lsb_release ]; then
-		lsb_release --id
+		lsb_release -si
 	else
 		echo "`basename $0:` lsb_release is not found"
 	fi
@@ -102,61 +89,67 @@ check_utils()
 	echo "USB utils ${USBUTILS}"
 }
 
-###################### BEGIN ######################
+main()
+{
+	local FILE_SIZE=$(cat /usr/share/mare/version.list | head -n1)
+	local BASH=0
+	local PACKAGE_MANAGER=0
+	local COMMAND="$1"
 
-if [ -z "$FILE_SIZE" ]; then
-	check_utils > /usr/share/mare/version.list
-fi
+	if [ -z "$FILE_SIZE" ]; then
+		check_utils > /usr/share/mare/version.list
+	fi
 
-BASH=$(grep "mare: bash is" /usr/share/mare/version.list)
-PACKAGE_MANAGER=$(grep "^m*a" /usr/share/mare/version.list)
+	BASH=$(grep "mare: bash is" /usr/share/mare/version.list)
+	PACKAGE_MANAGER=$(grep "^m*a" /usr/share/mare/version.list)
 
-if [ -z "$BASH" ]; then
-	if [ -z "$PACKAGE_MANAGER" ]; then
-		# Usage
-		while [ "$#" -gt 0 ]; do
-			case "$1" in
-				-n | --netbt )
-				/usr/lib/mare/netbt.sh
-				/usr/lib/mare/sudo.sh
-				;;
-				-d | --drivers )
-				/usr/lib/mare/drivers.sh
-				;;
-				-m | --motd )
-				/usr/lib/mare/motd.sh
-				;;
-				-h | --help )
-				cat /usr/share/mare/usage.list
-				exit 0 
-				;;
-				-v | --version )
-				cat /usr/share/mare/release.list
-				exit 0 
-				;;
-				* )
-				echo "`basename $0:` wrong key — «$1»"
-				echo "On command «mare --help» one can get additional information."
+	if [ -z "$BASH" ]; then
+		if [ -z "$PACKAGE_MANAGER" ]; then
+			# Usage
+			while [ "$#" -gt 0 ]; do
+				case "$1" in
+					-n | --netbt )
+					/usr/lib/mare/netbt.sh
+					/usr/lib/mare/sudo.sh
+					;;
+					-d | --drivers )
+					/usr/lib/mare/drivers.sh
+					;;
+					-m | --motd )
+					/usr/lib/mare/motd.sh
+					;;
+					-h | --help )
+					cat /usr/share/mare/usage.list
+					exit 0 
+					;;
+					-v | --version )
+					cat /usr/share/mare/release.list
+					exit 0 
+					;;
+					* )
+					echo "`basename $0:` wrong key — «$1»"
+					echo "On command «mare --help» one can get additional information."
+					exit 1
+    				;;
+    			esac
+				break
+			done
+
+			if [ -z "$COMMAND" ]; then
+				echo "`basename $0:` indicate required action"
+				echo "For help using the program, enter the command:"
+				echo "mare -h or mare --help."
 				exit 1
-    			;;
-    		esac
-			break
-		done
-
-		if [ -z "$COMMAND" ]; then
-			echo "`basename $0:` indicate required action"
-			echo "For help using the program, enter the command:"
-			echo "mare -h or mare --help."
+			fi
+			shift
+		else
+			echo "`basename $0:` you are using a different distribution GNU/Linux"
 			exit 1
 		fi
-		shift
 	else
-		echo "`basename $0:` you are using a different distribution GNU/Linux"
+		echo "`basename $0:` this script only works with bash"
 		exit 1
 	fi
-else
-	echo "`basename $0:` this script only works with bash"
-	exit 1
-fi
+}
 
-###################### END ######################
+main
