single distribution support returned

diff --git a/mare b/mare
--- a/mare
+++ b/mare
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 # mare - tool the home computer setup
-# Copyright (C) 2020 Alexandre Popov <amocedonian@gmail.com>.
+# Copyright (C) 2019 - 2020 Alexandre Popov <amocedonian@gmail.com>.
 #
 #   This program is free software: you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -17,35 +17,39 @@
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
+DISTRO=$(lsb_release --description | awk '{print $2, $3, $4}')
+DEBIAN_VERSION=$(cat /etc/debian_version | cut -d"." -f1)
 COMMAND="$1"
 
-# Usage
-while [ "$#" -gt 0 ]; do
-	case "$1" in
-		-m --menu )
-		/usr/share/mare/menu.sh
-		;;
-		-h | --help )
-		cat /usr/share/mare/data/usage.list
-		exit 0 
-		;;
-		-v | --version )
-		cat /usr/share/mare/data/release.list
-		exit 0 
-		;;
-		* )
-		echo "`basename $0:` wrong key — «$1»."
-		echo "On command «mare --help» one can get additional information."
-		exit 1
-    	;;
-    esac
-	break
-done
+if [ "$DISTRO" = "Debian GNU/Linux $DEBIAN_VERSION" ]; then
+	# Usage
+	while [ "$#" -gt 0 ]; do
+		case "$1" in
+			-h | --help )
+			cat /usr/share/mare/usage.list
+			exit 0 
+			;;
+			-v | --version )
+			cat /usr/share/mare/release.list
+			exit 0 
+			;;
+			* )
+			echo "`basename $0:` wrong key — «$1»."
+			echo "On command «mare --help» one can get additional information."
+			exit 1
+    		;;
+    	esac
+		break
+	done
 
-if [ -z "$COMMAND" ]; then
-	echo "`basename $0:` indicate required action."
-	echo "For help using the program, enter the command:"
-	echo "mare -h or mare --help."
+	if [ -z "$COMMAND" ]; then
+		echo "`basename $0:` indicate required action."
+		echo "For help using the program, enter the command:"
+		echo "mare -h or mare --help."
+		exit 1
+	fi
+	shift
+else
+	echo "`basename $0:` you are using a different distribution GNU/Linux."
 	exit 1
 fi
-shift
