script menu added

diff --git a/mare b/mare
--- a/mare
+++ b/mare
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# mare - menu
+# mare - tool the home computer setup
 # Copyright (C) 2020 Alexandre Popov <amocedonian@gmail.com>.
 #
 #   This program is free software: you can redistribute it and/or modify
@@ -17,76 +17,35 @@
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-#################################
-#           VARIABLES           #
-#################################
+COMMAND="$1"
 
-# Variable for selecting an operation in a script
-CHOICE=0
-# Variable to enter the return symbol
-DUMMY=0
-
-###################### BEGIN ######################
-
-# endless loop creates a script menu
-while :
-do
-	cat /usr/share/mare/data/menu.list
-	echo -n "Your Choice [1,2,3,4,5,6,7,8,9,10,11,12,H,Q] > "
-	read CHOICE
-	
-	case "$CHOICE" in
-		1 )
-		/usr/share/mare/network.sh
+# Usage
+while [ "$#" -gt 0 ]; do
+	case "$1" in
+		-m --menu )
+		/usr/share/mare/menu.sh
 		;;
-		2 )
-		/usr/share/mare/wificon.sh
+		-h | --help )
+		cat /usr/share/mare/data/usage.list
+		exit 0 
 		;;
-		3 )
-		/usr/share/mare/sudo.sh
-		;;
-		4 )
-		/usr/share/mare/sysupdate.sh
-		;;
-		5 )
-		/usr/share/mare/drivers.sh
-		;;
-		6 )
-		/usr/share/mare/grub.sh
-		;;
-		7 )
-		/usr/share/mare/fstab.sh
-		;;
-		8 )
-		/usr/share/mare/optimization.sh
-		;;
-		9 )
-		/usr/share/mare/packages.sh
-		;;
-		10 )
-		/usr/share/mare/codecs.sh
-		;;
-		11 )
-		/usr/share/mare/motd.sh
-		;;
-		12 )
-		/usr/share/mare/dm.sh
-		;;
-		H | h )
-		man mare
-		;;
-		Q | q )
-		exit 0
+		-v | --version )
+		cat /usr/share/mare/data/release.list
+		exit 0 
 		;;
 		* )
-		echo "`basename $0:` unknown user response"
+		echo "`basename $0:` wrong key — «$1»."
+		echo "On command «mare --help» one can get additional information."
 		exit 1
-		;;
-	esac
-	echo "Hit the return key to continue "
-	read DUMMY
-	# clear screen
-	clear
+    	;;
+    esac
+	break
 done
-	
-###################### END ######################
+
+if [ -z "$COMMAND" ]; then
+	echo "`basename $0:` indicate required action."
+	echo "For help using the program, enter the command:"
+	echo "mare -h or mare --help."
+	exit 1
+fi
+shift
