programming style changed and path to shell changed

diff --git a/mare b/mare
--- a/mare
+++ b/mare
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 #
 # mare - tool the home computer setup
 #
@@ -20,6 +20,29 @@
 
 LC_ALL=C
 export LC_ALL
+
+check_root()
+{
+	local USER_ID=$(id -u)
+	
+	if [ "$USER_ID" = "0" ]; then
+		check_file_size
+		check_shell
+	else
+		echo "`basename $0:` root is not found"
+		echo "Run the mare script as root."
+		exit 1
+	fi
+}
+
+check_file_size()
+{
+	local FILE_SIZE=$(cat /usr/share/mare/version.list | head -n1)
+	
+	if [ -z "$FILE_SIZE" ]; then
+		check_utils > /usr/share/mare/version.list
+	fi
+}
 
 # Check used tools for their presence in the operating system
 check_utils()
@@ -76,8 +99,6 @@ check_utils()
 	wget --version | head -n1 | cut -d" " -f1-3
 	update-grub --version
 	grep --version | head -n1
-	PERL=$(perl -V:version | cut -d"'" -f2)
-	echo "Perl ${PERL}" 
 	python3 --version
 	ip -Version
 
@@ -89,67 +110,75 @@ check_utils()
 	echo "USB utils ${USBUTILS}"
 }
 
-main()
+check_shell()
 {
-	local FILE_SIZE=$(cat /usr/share/mare/version.list | head -n1)
-	local BASH=0
-	local PACKAGE_MANAGER=0
-	local COMMAND="$1"
-
-	if [ -z "$FILE_SIZE" ]; then
-		check_utils > /usr/share/mare/version.list
-	fi
-
-	BASH=$(grep "mare: bash is" /usr/share/mare/version.list)
-	PACKAGE_MANAGER=$(grep "^m*a" /usr/share/mare/version.list)
-
+	local BASH=$(grep "mare: bash is" /usr/share/mare/version.list)
+	
 	if [ -z "$BASH" ]; then
-		if [ -z "$PACKAGE_MANAGER" ]; then
-			# Usage
-			while [ "$#" -gt 0 ]; do
-				case "$1" in
-					-n | --netbt )
-					/usr/lib/mare/netbt.sh
-					/usr/lib/mare/sudo.sh
-					;;
-					-d | --drivers )
-					/usr/lib/mare/drivers.sh
-					;;
-					-m | --motd )
-					/usr/lib/mare/motd.sh
-					;;
-					-h | --help )
-					cat /usr/share/mare/usage.list
-					exit 0 
-					;;
-					-v | --version )
-					cat /usr/share/mare/release.list
-					exit 0 
-					;;
-					* )
-					echo "`basename $0:` wrong key — «$1»"
-					echo "On command «mare --help» one can get additional information."
-					exit 1
-    				;;
-    			esac
-				break
-			done
-
-			if [ -z "$COMMAND" ]; then
-				echo "`basename $0:` indicate required action"
-				echo "For help using the program, enter the command:"
-				echo "mare -h or mare --help."
-				exit 1
-			fi
-			shift
-		else
-			echo "`basename $0:` you are using a different distribution GNU/Linux"
-			exit 1
-		fi
+		check_package_manager
 	else
 		echo "`basename $0:` this script only works with bash"
 		exit 1
 	fi
+}
+
+check_package_manager()
+{
+	local PACKAGE_MANAGER=$(grep "^m*a" /usr/share/mare/version.list)
+	
+	if [ -z "$PACKAGE_MANAGER" ]; then
+		usage
+	else
+		echo "`basename $0:` you are using a different distribution GNU/Linux"
+		exit 1
+	fi
+}
+
+usage()
+{
+	local COMMAND="$1"
+
+	while [ "$#" -gt 0 ]; do
+		case "$1" in
+			-i | --ifaces )
+			/usr/lib/mare/ifaces.sh
+			/usr/lib/mare/sudo.sh
+			;;
+			-v | --vcards )
+			/usr/lib/mare/vcards.sh
+			;;
+			-m | --motd )
+			/usr/lib/mare/motd.sh
+			;;
+			-h | --help )
+			cat /usr/share/mare/usage.list
+			exit 0 
+			;;
+			-V | --version )
+			cat /usr/share/mare/release.list
+			exit 0 
+			;;
+			* )
+			echo "`basename $0:` wrong key — «$1»"
+			echo "On command «mare --help» one can get additional information."
+			exit 1
+    		;;
+    	esac
+		break
+	done
+
+	if [ -z "$COMMAND" ]; then
+		echo "`basename $0:` indicate required action"
+		echo "For help using the program, enter the command:"
+		echo "mare -h or mare --help."
+		exit 1
+	fi
+	shift
+}
+
+main()
+{
+	check_root
 }
 
 main
